[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
description = "A fork of the uplc-turbo crate tailored for usage within Pallas"
edition = "2021"
license = "Apache-2.0"
authors = ["TxPipe <hello@txpipe.io>"]
repository = "https://github.com/txpipe/uplc-turbo"
homepage = "https://github.com/txpipe/uplc-turbo"
documentation = "https://docs.rs/pallas-uplc"
